datetime client
codescalersinternships/Datetime-client-RawanMostafa pull request #1
Opened 2024-09-21 22:21 UTC by RawanMostafa08

Issue link: https://github.com/codescalersinternships/home/issues/288
This PR implements the first version of a datetime client

2024-09-30 10:01 UTC, Eslam-Nawara requested changes

2024-09-30 10:01 UTC, Eslam-Nawara commented on cmd/main.go
> +func decideConfigs() (string, string, string) {
ensureConfig/loadConfig, you're loading configurations then ensuring that all were set no?

2024-09-30 10:01 UTC, Eslam-Nawara commented on cmd/main.go
> +		}
we can skip the extra else like this
```suggestion
		var found bool
		baseUrl, found = os.LookupEnv("DATETIME_BASEURL")
		if !found {
			baseUrl = defaltBaseUrl
		}

```

2024-09-30 10:01 UTC, Eslam-Nawara commented on cmd/main.go
> +		}
same for all

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +	contentType string
I don't think you need to store the content type in the client, the same client can be used to fetch more than one content type

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +func NewClient(baseUrl string, endpoint string, port string, contentType string, timeout time.Duration) Client {
timeout should be an option with default value say 10s

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +		port:        port,
you can create and store only the request url instead of storing this data

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +func (c Client) GetTime() (time.Time, error) {
I think content type should be passed as an argument here

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +	expBackoff.MaxElapsedTime = 10 * time.Second
that's very small duration

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client.go
> +	}
I think you need to check if the status code is not status ok before reading the body

2024-09-30 10:01 UTC, Eslam-Nawara commented on pkg/client_test.go
> +			mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
please create the mockserver in a helper function

2024-10-01 20:48 UTC, RawanMostafa08 commented on pkg/client.go
> +	contentType string
I think this is a matter of opinion as Abdulrahman told me that configs should have the data type so I did it this way, It was an argument to the function before

2024-10-01 20:49 UTC, RawanMostafa08 commented on pkg/client.go
> +func NewClient(baseUrl string, endpoint string, port string, contentType string, timeout time.Duration) Client {
what do you mean by an option? you mean optional parameter? isn't this not supported in go?

2025-01-13 08:59 UTC, xmonader approved these changes

2025-01-13 09:01 UTC, merged